"""reset migraciones

Revision ID: ddc0f10054bd
Revises: 
Create Date: 2026-03-14 15:08:27.010690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc0f10054bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banco',
    sa.Column('id_banco', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_banco', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_banco')
    )
    op.create_table('categoria_finanza',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('categoria_habito',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('ejercicios',
    sa.Column('id_ejercicio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('bicep', 'tricep', 'pecho', 'hombro', 'espalda', 'cuadricep', name='musculos'), nullable=False),
    sa.Column('url_video', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_ejercicio')
    )
    op.create_table('gimnasio',
    sa.Column('id_gimnasio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_gimnasio', sa.String(), nullable=False),
    sa.Column('nombre_cadena', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('comuna', sa.String(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_gimnasio'),
    sa.UniqueConstraint('direccion'),
    sa.UniqueConstraint('nombre_gimnasio')
    )
    op.create_table('libros',
    sa.Column('id_libro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_libro', sa.String(), nullable=False),
    sa.Column('nombre_autor', sa.String(), nullable=False),
    sa.Column('total_paginas', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_libro'),
    sa.UniqueConstraint('nombre_libro')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('auth_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('auth_user_id'),
    sa.UniqueConstraint('telefono'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('cuenta_bancaria',
    sa.Column('id_cuenta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_banco', sa.Integer(), nullable=False),
    sa.Column('nombre_cuenta', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('tipo_cuenta', sa.Enum('Cuenta Corriente', 'Cuenta vista', 'Cuenta ahorro', name='cuentas_bancarias'), server_default='Cuenta vista', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_banco'], ['banco.id_banco'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cuenta')
    )
    op.create_table('entrenamiento',
    sa.Column('id_entrenamiento', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_entrenamiento', sa.Enum('fuerza', 'cardio', name='tipo_entrenamiento'), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_entrenamiento')
    )
    op.create_table('habito',
    sa.Column('id_habito', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('frecuencia', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_habito.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_habito')
    )
    op.create_table('lectura',
    sa.Column('id_lectura', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('terminado', 'en_proceso', 'abandonado', 'sin_comenzar', name='estado_lectura'), server_default='sin_comenzar', nullable=False),
    sa.ForeignKeyConstraint(['id_libro'], ['libros.id_libro'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_lectura')
    )
    op.create_table('mensaje',
    sa.Column('id_mensaje', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_table('entrenamiento_aerobico',
    sa.Column('id_aerobico', sa.Integer(), nullable=False),
    sa.Column('id_entrenamiento', sa.Integer(), nullable=False),
    sa.Column('tipo_aerobico', sa.Enum('bicicleta', 'correr', 'natacion', name='tipo aerobico'), nullable=False),
    sa.Column('distancia_km', sa.Float(), nullable=False),
    sa.Column('duracion_segundos', sa.Integer(), nullable=False),
    sa.Column('calorias', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_entrenamiento'], ['entrenamiento.id_entrenamiento'], ),
    sa.PrimaryKeyConstraint('id_aerobico'),
    sa.UniqueConstraint('id_entrenamiento')
    )
    op.create_table('entrenamiento_fuerza',
    sa.Column('id_entrenamiento_fuerza', sa.Integer(), nullable=False),
    sa.Column('id_entrenamiento', sa.Integer(), nullable=False),
    sa.Column('id_gimnasio', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'cerrado', name='estado_entrenamiento_fuerza'), server_default='activo', nullable=False),
    sa.Column('inicio_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fin_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_entrenamiento'], ['entrenamiento.id_entrenamiento'], ),
    sa.ForeignKeyConstraint(['id_gimnasio'], ['gimnasio.id_gimnasio'], ),
    sa.PrimaryKeyConstraint('id_entrenamiento_fuerza'),
    sa.UniqueConstraint('id_entrenamiento')
    )
    op.create_table('movimiento',
    sa.Column('id_transaccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_cuenta', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('gasto', 'ingreso', name='tipo_movimiento'), nullable=False),
    sa.Column('tipo_gasto', sa.Enum('variable', 'fijo', name='tipo_gasto'), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_finanza.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuenta_bancaria.id_cuenta'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_transaccion')
    )
    op.create_table('registro_habito',
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('id_habito', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_habito'], ['habito.id_habito'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    op.create_table('registro_lectura',
    sa.Column('id_registro', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_lectura', sa.BigInteger(), nullable=False),
    sa.Column('pagina_inicio', sa.Integer(), nullable=False),
    sa.Column('pagina_final', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_lectura'], ['lectura.id_lectura'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    op.create_table('serie_fuerza',
    sa.Column('id_fuerza_detalle', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_entrenamiento_fuerza', sa.Integer(), nullable=False),
    sa.Column('id_ejercicio', sa.Integer(), nullable=False),
    sa.Column('es_calentamiento', sa.Boolean(), nullable=False),
    sa.Column('cantidad_peso', sa.Float(), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ejercicio'], ['ejercicios.id_ejercicio'], ),
    sa.ForeignKeyConstraint(['id_entrenamiento_fuerza'], ['entrenamiento_fuerza.id_entrenamiento_fuerza'], ),
    sa.PrimaryKeyConstraint('id_fuerza_detalle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serie_fuerza')
    op.drop_table('registro_lectura')
    op.drop_table('registro_habito')
    op.drop_table('movimiento')
    op.drop_table('entrenamiento_fuerza')
    op.drop_table('entrenamiento_aerobico')
    op.drop_table('mensaje')
    op.drop_table('lectura')
    op.drop_table('habito')
    op.drop_table('entrenamiento')
    op.drop_table('cuenta_bancaria')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('libros')
    op.drop_table('gimnasio')
    op.drop_table('ejercicios')
    op.drop_table('categoria_habito')
    op.drop_table('categoria_finanza')
    op.drop_table('banco')
    # ### end Alembic commands ###
